version: '3.0'

services:
  grafana:
    platform: 'linux/amd64'
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-12.4.3}
    ports:
      - 3000:3000/tcp
    environment:
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
