name: Combine PRs

on:
  workflow_dispatch: # manual activation, for now

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.2.0
        with:
          labels: combined-pr
          pr_title: "Dependabot updates"
          branch_prefix: dependabot # the default, just for clarity
