name: Dependabot reviewer
on: pull_request
permissions:
  pull-requests: write
  contents: write
jobs:
  call-workflow-passing-data:
    uses: grafana/security-github-actions/.github/workflows/dependabot-automerge.yaml@main
    with:
      packages-minor-autoupdate: '["@emotion/css","@grafana/async-query-data","@grafana/data","@grafana/plugin-ui","@grafana/runtime","@grafana/schema","@grafana/ui","semver","tslib","github.com/aws/aws-sdk-go-v2","github.com/aws/aws-sdk-go-v2/service/athena","github.com/google/go-cmp","github.com/grafana/grafana-aws-sdk","github.com/grafana/grafana-plugin-sdk-go","github.com/grafana/sqlds/v4","github.com/pkg/errors","github.com/stretchr/testify","github.com/uber/athenadriver","github.com/viant/toolbox","gotest.tools"]'
      repository-merge-method: 'squash'
