name: Run commands when issues are labeled
on:
  issues:
    types: [labeled, unlabeled]
permissions: {}
jobs:
  main:
    permissions:
      contents: read
      id-token: write # Required by create-github-app-token
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: 'grafana/grafana-github-actions'
          path: ./actions
          ref: main
          persist-credentials: false
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Get GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: aws-ds-token-creator
      - name: Run Commands
        uses: ./actions/commands
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          configPath: issue_commands
