name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  log:
    name: Log Environment Variable
    runs-on: ubuntu-latest
    steps:
      - name: Log env variables
        run: echo "Event name is '${{ github.event_name }}', repo name in CI is '${{ github.event.pull_request.head.repo.full_name }}', and GitHub repo is '${{ github.repository }}'"
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main # zizmor: ignore[unpinned-uses]
    permissions:
      contents: read
      id-token: write
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      golangci-lint-version: '2.0.2'
      playwright-secrets: |
        ACCESS_KEY=e2e:accessKey
        SECRET_KEY=e2e:secretKey
