name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ddc6565117d4fd559e0f22c4f9cf1ac76c229e14 # ci-cd-workflows/v3
    permissions:
      contents: read
      id-token: write
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      golangci-lint-version: '2.0.2'
      playwright-config: ${{ github.event.pull_request.head.repo.fork == true || github.actor == 'dependabot[bot]' && 'playwright-fork.config.ts' || 'playwright.config.ts' }}
      playwright-secrets: |
        ACCESS_KEY=e2e:accessKey
        SECRET_KEY=e2e:secretKey
